import { NextResponse } from "next/server";

export async function GET() {
    const feedback = {
        ticketDescription: "Ticket 12 - Error Handling",
        mustData: [
            {
                guidance: "The app is deployed on netlify with a working link",
                www: "App is deployed",
                ebi: "Please deploy your app",
            },
            {
                guidance:
                    "Refreshing the app on sub routes has no errors, guide to fixing them - guide to fix here - https://ridbay.medium.com/react-routing-and-netlify-redirects-fd1f00eeee95",
                www: "Sub routes work",
                ebi: "Sub routes dont seem to work - look here on how to fix it - https://ridbay.medium.com/react-routing-and-netlify-redirects-fd1f00eeee95",
            },
            {
                guidance:
                    "Production deployments are used. Url should be of the form https://students-app-name.netlify.app/ and not https://1234abcd12acde000111cdef--students-app-name.netlify.app. This is a preview url generated by netlify deploy. Use netlify deploy --prod to resolve",
                www: "Good production deployment",
                ebi: "Use netlify deploy --prod to resolve your URL to something a bit more production ready",
            },
        ],
        shouldData: [],
        couldData: [],
    };

    return NextResponse.json({ feedback });
}
